version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "4200:80" # host:container -> ip:4200 maps ip:4200 to container:80

  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    volumes: # maps directory relative to docker-compose.yml to container directory
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - /backend/node_modules:/app/node_modules

  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
