version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "4200:4200"
    volumes: # maps directory relative to docker-compose.yml to container directory
      - ./frontend:/app/dist/peakvisor

  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /app/dist/peakvisor:/usr/share/nginx/html

